#ifndef RESOURCETYPE_H_
#define RESOURCETYPE_H_

enum TEXTURE_ID
{
    NONE = 0,
    FLOOR = 1,
    FLOOR_TRIGGER = 2,
    WALL = 3,
    PLAYER_SPAWN = 4,
    PLAYER = 5,
    OBJECT = 6,
    OBJECT_GLOW = 7,
    UI_BACKGROUND = 8,
    
	UI_LOGO = 20,
	UI_PLAY = 21,
	UI_PLAY_ACTIVE = 22,
	UI_ABOUT = 23,
	UI_ABOUT_ACTIVE = 24,
	UI_EXIT = 25,
	UI_EXIT_ACTIVE = 26,
};

#define MAP_ELEMENT TEXTURE_ID

#endif // RESOURCETYPE_H_
